# Generated by Django 6.0.3 on 2026-03-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
    ]
